server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /descubriendo-el-proposito/ {
        try_files $uri $uri/ /descubriendo-el-proposito/index.html;
    }

    location /images/ {
        alias /usr/share/nginx/html/descubriendo-el-proposito/images/;
    }

    location = / {
        return 301 /descubriendo-el-proposito/;
    }
}
